version: "3.4"
services:
  prysm-medalla-validator.dnp.dappnode.eth:
    image: "prysm-medalla-validator.dnp.dappnode.eth:1.0.9"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.0.0-beta.0
    volumes:
      - "data:/data"
    ports:
      - "13000"
      - "12000"
      - "7500:7500"
    restart: always
    environment:
      BEACON_RPC_PROVIDER: "http://prysm-zinken-beacon-chain.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
volumes:
  data: {}
