version: "3.4"
services:
  prysm-medalla-validator.dnp.dappnode.eth:
    image: "prysm-medalla-validator.dnp.dappnode.eth:1.0.9"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.0.0-beta.0
    volumes:
      - "data:/root/.eth2"
      - "validators:/root/.eth2validators"
    restart: always
    environment:
      BEACON_RPC_PROVIDER: "prysm-medalla-beacon-chain.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
volumes:
  data: {}
  validators: {}
